version: "3.8"

services:
  fabstir-ai-vector-db:
    build: .
    container_name: fabstir-ai-vector-db-container
    volumes:
      # Mount the current directory (fabstir.ai vector database project)
      - .:/home/developer/fabstir-ai-vector-db
      # Create named volumes for persistence
      - npm-cache:/home/developer/.npm
      - cargo-cache:/home/developer/.cargo
      - vector-data:/home/developer/fabstir-ai-vector-db/data
      # Mount enhanced s5.js as a dependency (optional - adjust path as needed)
      # - ../enhanced-s5js:/home/developer/enhanced-s5js:ro
    ports:
      - "7530:7530" # Vector Database API
      - "7531:7531" # MCP Server
      - "7532:7532" # Admin/Debug interface
    environment:
      - NODE_ENV=development
      - VECTOR_DB_PORT=7530
      - MCP_SERVER_PORT=7531
      - ADMIN_PORT=7532
      # S5 Portal configuration
      - S5_PORTAL_URL=${S5_PORTAL_URL:-https://s5.vup.cx}
      # S5 seed phrase (optional - can be generated by the app if not provided)
      - S5_SEED_PHRASE=${S5_SEED_PHRASE}
      # Vector database configuration
      - VECTOR_DIMENSION=${VECTOR_DIMENSION:-1536} # Default for OpenAI embeddings
      - MAX_VECTORS_PER_INDEX=${MAX_VECTORS_PER_INDEX:-1000000}
      - HAMT_BRANCHING_FACTOR=${HAMT_BRANCHING_FACTOR:-32}
      # HAMT sharding threshold (matches S5 implementation)
      - HAMT_ACTIVATION_THRESHOLD=${HAMT_ACTIVATION_THRESHOLD:-1000}
    stdin_open: true
    tty: true
    networks:
      - fabstir-network
    # Health check for the vector database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7530/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching (remove if not needed)
  redis:
    image: redis:7-alpine
    container_name: fabstir-ai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - fabstir-network
    command: redis-server --appendonly yes

volumes:
  npm-cache:
  cargo-cache:
  vector-data:
  redis-data:

networks:
  fabstir-network:
    driver: bridge
